---
version: '2'
name: bop
services:

  # NOTE: we're fine with using Docker local volumes; it shouldn't be much data.
  zookeeper:
    image: harvardcga/zookeeper:3.4
    ports:
      - "2181:2181"
    environment:
      #ZOO_MY_ID: 1  (automatic using KONTENA_SERVICE_INSTANCE_NUMBER in the entrypoint script)
      ZOO_SERVERS: server.1=${project}-zookeeper-1:2888:3888 server.2=${project}-zookeeper-2:2888:3888 server.3=${project}-zookeeper-3:2888:3888
      ZOO_AUTOPURGE_PURGE_INTERVAL: 24
    deploy:
      wait_for_port: 2181
      # Kontena doesn't start zk properly without this:
      min_health: 0.0
    instances: 3
    affinity:
      # Run Zookeeper on the first three Solr nodes (same host as Solr).
      # %%i is instance id
      - node==bop-solr-%%i.novalocal
    stateful: true

  # For Solr, we treat bop-solr-1 kinda special in that we deliberately do various processing on
  # this node: RT shard is here, SolrCloud's Overseer is here, the node also runs bop-webservice
  # and bop-ingest, and searches
  # go here, new data always comes here first. But not much data here. The primary shards are all
  # on the other nodes.
  solr:
    image: harvardcga/solr
    # SolrCloud mode, remote zookeeper.
    command: -c -z ${project}-zookeeper-1:2181,${project}-zookeeper-2:2181,${project}-zookeeper-3:2181
    environment:
      SOLR_HEAP: 4G
      ENABLE_REMOTE_JMX_OPTS: true #port 18983
      #TODO softcommit: only on "RT"?  Otherwise use 1 hour?
      # poll-queue-time: SOLR-7333 default is 25ms but way too small IMO.
      SOLR_OPTS:
        -Dsolr.autoSoftCommit.maxTime=5000
        -Dsolr.cloud.replication.poll-queue-time-ms=1000
        -Dsolr.cloud.replication.runners=2
#    hooks:
#      post_start:
#        # Note we have a collection replica placement rule that uses this role.
#        - name: add overseer role to first node
#          cmd: sleep 8 && wget -qO- 'http://localhost:8983/solr/admin/collections?action=ADDROLE\&role=overseer\&node=bop-solr-1.kontena.local:8983_solr'
#          instances: 1
#          oneshot: true
      #TODO log WARN org.apache.solr.core.SolrCore.Request  ?
    depends_on:
      - zookeeper
    deploy:
      wait_for_port: 8983
      min_health: 0.0
    instances: 4 #TODO 5
    affinity:
      # %%i is instance id
      - node==bop-solr-%%i.novalocal
    stateful: true
    volumes:
      - /opt/solr/server/solr/

  webservice:
    image: harvardcga/bop-webservice
    build: ./webservice
    hooks:
      pre_build:
        - name: maven
          cmd: cd webservice && mvn -DskipTests clean validate assembly:assembly
    ports:
      - 8080:8080
    depends_on:
      - solr
    external_links:
      - loadbalancer-loadbalancer
    environment:
      # see bop-ws.yml
      #dw.logging.level: DEBUG
      dw.solrUrl: http://${project}-solr-3:8983/solr
      dw.solrCollection: bop
      dw.server.applicationContextPath: /bopws
      JMX:
        -Dcom.sun.management.jmxremote=true
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.rmi.port=9999
        -Dcom.sun.management.jmxremote.port=9999
      JAVA_OPTS: -Xmx512M
      KONTENA_LB_INTERNAL_PORT: 8080
      KONTENA_LB_VIRTUAL_PATH: /bopws
      KONTENA_LB_KEEP_VIRTUAL_PATH: true
    deploy:
      wait_for_port: 8080
    affinity:
      - node==bop-solr-3.novalocal

  ingest:
    image: harvardcga/bop-ingest
    build: ./ingest
    hooks:
      pre_build:
        - name: maven
          cmd: cd ingest && mvn -DskipTests clean validate assembly:assembly
    depends_on:
      - solr
    external_links:
      - kafka-kafka
      - kafka-zookeeper
    environment:
      # see dw.yml
      dw.kafkaSourceTopic: tweets-enriched2
      dw.kafkaConsumer.auto-offset-reset: earliest
      dw.kafkaConsumer.bootstrap-servers: kafka-kafka-1:9092,kafka-kafka-2:9092
      dw.kafkaConsumer.zookeeper-connect: kafka-zookeeper-1:2181,kafka-zookeeper-2:2181,kafka-zookeeper-3:2181
      dw.kafkaConsumer.group-id: bop-ingest-bopcollection
      # We send to the node containing "RT" (most likely where needed, and kinda needed for our date URP)
      dw.solrConnectionString: http://${project}-solr-1:8983/solr/
      dw.solrCollection: bop #note: update dw.kafkaConsumer.group-id accordingly
      JMX:
        -Dcom.sun.management.jmxremote=true
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.rmi.port=9999
        -Dcom.sun.management.jmxremote.port=9999
      # NewRatio=1 means 1/2 heap is for young gen since this is ETL.
      JAVA_OPTS: -XX:NewRatio=1 -Xmx750M
    affinity:
      - node==bop-solr-1.novalocal