---
version: '2'
services:
  
  # note: only need to open ports if wish to communicate with either from *outside* the docker engine.
  
  zookeeper:
    image: confluentinc/cp-zookeeper:3.0.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: harvardcga/cp-kafka:3.0.1
    # customized to fix: https://github.com/confluentinc/cp-docker-images/pull/141
    build:
      context: "."
      dockerfile: kafka.Dockerfile
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #  ${HOSTNAME} should be an IP or name resolveable by clients communicating with Kafka. And NOT 127.0.0.1 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOSTNAME}:9092