---
version: '2'
name: kafka
services:
  
  # HA configuration. See https://github.com/confluentinc/cp-docker-images/blob/master/examples/kafka-cluster/docker-compose.yml
  # NOTE: we're fine with using Docker local volumes; it shouldn't be much data.
  zookeeper:
    image: harvardcga/zookeeper:3.4
    build:
      context: "."
      dockerfile: zookeeper.Dockerfile
    stateful: true
    instances: 3
    affinity:
      - label==kafka
    ports:
      - "2181:2181"
    deploy:
      wait_for_port: 2181
      min_health: 0.5
    environment:
      #ZOO_MY_ID: 1  (automatic using KONTENA_SERVICE_INSTANCE_NUMBER in the entrypoint script)
      ZOO_SERVERS: server.1=${project}-zookeeper-1:2888:3888 server.2=${project}-zookeeper-2:2888:3888 server.3=${project}-zookeeper-3:2888:3888
      ZOO_AUTOPURGE_PURGE_INTERVAL: 24

  kafka:
    image: harvardcga/cp-kafka:3.1.2-hcga2
    build:
      context: "."
      dockerfile: kafka.Dockerfile
    depends_on:
      - zookeeper
    stateful: true
    instances: 3
    deploy:
      wait_for_port: 9092
    affinity:
      # %%i is instance id
      - node==kafka%%i.novalocal
    volumes:
      - /media/attached/kafka/data:/var/lib/kafka/data
    environment:
      #KAFKA_BROKER_ID: 1
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${project}-kafka-1.kontena.local:9092
      KAFKA_ZOOKEEPER_CONNECT: ${project}-zookeeper-1:2181,${project}-zookeeper-2:2181,${project}-zookeeper-3:2181
      KAFKA_DELETE_TOPIC_ENABLE: true
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_COMPRESSION_TYPE: lz4
      KAFKA_JMX_PORT: 9999

  kafka-manager:
    image: harvardcga/kafka-manager
    build:
      # we make the http context path configurable (and do some other housekeeping).
      context: ./
      dockerfile: kafka-manager.Dockerfile
    # (not stateful; state is saved into ZK)
    depends_on:
      - zookeeper
      - kafka
    external_links:
      - loadbalancer-loadbalancer
    environment:
      ZK_HOSTS: ${project}-zookeeper-1:2181,${project}-zookeeper-2:2181,${project}-zookeeper-3:2181
      KONTENA_LB_INTERNAL_PORT: 9000
      KONTENA_LB_VIRTUAL_PATH: /kafka-manager/
      KONTENA_LB_KEEP_VIRTUAL_PATH: true
      KM_HTTP_CONTEXT: /kafka-manager/
      KM_USERNAME: "admin"
    deploy:
      wait_for_port: 9000
      interval: 2d
    secrets:
      - secret: KAFKA_MANAGER_PASSWORD
        name: KM_PASSWORD
        type: env
