---
version: '2'
name: kafka
services:
  
  # HA configuration. See https://github.com/confluentinc/cp-docker-images/blob/master/examples/kafka-cluster/docker-compose.yml
  # NOTE: we're fine with using Docker local volumes; it shouldn't be much data.
  # TODO Zookeeper 3.4.7 would be nicer (than 3.4.6) in a docker env due to ZOOKEEPER-1506
  zookeeper1:
    extends:
      file: docker-compose.yml
      service: zookeeper
    stateful: true
    deploy:
      wait_for_port: 2181
    affinity:
      - node==kafka1.novalocal
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: ${project}-zookeeper1:22888:23888;${project}-zookeeper2:22888:23888;${project}-zookeeper3:22888:23888
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: 24
      # Confluent's image uses "KAFKA_JMX_*" even for ZooKeeper
      #KAFKA_JMX_PORT: 9999
      #KAFKA_JMX_HOSTNAME: ${project}-zookeeper-1.kontena.local

  zookeeper2:
    extends:
      service: zookeeper1
    affinity:
      - node==kafka2.novalocal
    environment:
      ZOOKEEPER_SERVER_ID: 2

  zookeeper3:
    extends:
      service: zookeeper1
    affinity:
      - node==kafka3.novalocal
    environment:
      ZOOKEEPER_SERVER_ID: 3

  #TODO HA configuration. See https://github.com/confluentinc/cp-docker-images/blob/master/examples/kafka-cluster/docker-compose.yml
  kafka:
    extends:
      file: docker-compose.yml
      service: kafka
    stateful: true
    deploy:
      wait_for_port: 9092
    affinity:
      - node==kafka1.novalocal
    volumes:
      - /media/attached/kafka/data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ${project}-zookeeper.kontena.local:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${project}-kafka-1.kontena.local:9092
      KAFKA_DELETE_TOPIC_ENABLE: true
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${project}-kafka-1.kontena.local
      
  kafka-manager:
    image: harvardcga/kafka-manager
    build:
      # we make the http context path configurable (and do some other housekeeping).
      context: ./
      dockerfile: kafka-manager.Dockerfile
    # (not stateful; state is saved into ZK)
    depends_on:
      - zookeeper
      - kafka
    external_links:
      - loadbalancer-loadbalancer
    environment:
      ZK_HOSTS: ${project}-zookeeper.kontena.local:2181
      KONTENA_LB_INTERNAL_PORT: 9000
      KONTENA_LB_VIRTUAL_PATH: /kafka-manager
      KONTENA_LB_KEEP_VIRTUAL_PATH: true
      KM_HTTP_CONTEXT: /kafka-manager
      KM_USERNAME: "admin"
    deploy:
      wait_for_port: 9000
      interval: 2d
    secrets:
      - secret: KAFKA_MANAGER_PASSWORD
        name: KM_PASSWORD
        type: env

#TODO 3 zk services
#TODO 2 kafka services